### ISSUE TITLE
エラー時にローディング画面が表示され続ける。

### ISSUE THREAD

**Issue by rorenge7** [mistake-git/fmap-front#45]
エラー発生時にローディング画面が表示され続けている。
ユーザにエラーの情報を表示するようにする。

(ローディング画面)
![image](https://user-images.githubusercontent.com/38624583/104128264-efa3cd00-53a9-11eb-9127-b4d7f4094945.png)

**Comment by mistake-git** [comment]
alertを表示するようにして修正
