### ISSUE TITLE
認証のセキュリティ向上

### ISSUE THREAD

**Issue by rorenge7** [mistake-git/fmap-front#46]
https://github.com/mistake-git/fmap/blob/04e0d0224bd73a11dba4a9d2ff6e7691e819e2ba/front/src/Auth.tsx#L1-L34

contextでユーザ情報を保存してますが、悪意あるユーザがcontextを自分でいじることもできてしまう。
またサーバ側ではユーザを認証（=通信している相手が本人かどうか確認）しておらず、IDだけでどのユーザが判断している。
これだと例えば、他のユーザの情報を盗み見られたときに、それを使ってなりすまして投稿、みたいなことも可能😱

# 結論 JWTの導入

対策としてJWTを使用すべき。

# JWTの流れ
[JWT利用したFirebase+React+Railsでの認証の流れ](https://k-sato-blog.netlify.app/firebase-react-rails)

> (1) クライアントでEmail, Passwrordを入力し、Firebaseでユーザー検証 (Email, Passwordが違ったらログインできない)
→
(2) Email, PasswordがOKならTokenがFirebaseから渡される。
(この時点でアプリケーションはユーザーが存在する事を保証)
→
(3) 受け取ったTokenと共にリクエストをRailsに送る。
→
(4) RailsでTokenの検証(受け取ったTokenが変更されてないか検証)
(JWTのヘッダー、ペイロードが改変されていると、発行元Firebaseの署名と不一致になる)
=
!!! Tokenが正しい秘密鍵から作られているか公開鍵で検証(この場合はFirebaseの秘密鍵から作られたTokenか、Firebaseの公開鍵から検証) !!

## 1.トークン取得

[トークンの取り出し方](https://qiita.com/TanakanoAnchan/items/ce548c637bffb3c16687)
``` GetToken.tsx
// メール認証
  firebase.auth().signInWithEmailAndPassword(email, password)
    .then((result) => {
      const firebaseAuthUser = result.user;
      firebaseAuthUser.getIdToken(true)
        .then((idToken) => {
          console.log(idToken);
        })
        .catch((error) => {
          console.log(error);
        });
    })
    .catch(function (error) {
      console.log(error);
    });
```
[Firebase 公式記事](https://firebase.google.com/docs/auth/admin/create-custom-tokens?hl=ja)

## 2.トークンをAPIに投げる
リクエストが発生するたびに、フロント側で取り出したトークンも一緒に送るようにする。
myHttpClientとかで追加すると良さそう。

## 3.API側で認証

API側で送られてきたJWTで認証する。

- [流れと同じ記事](https://k-sato-blog.netlify.app/firebase-react-rails#firebase-%E3%81%8B%E3%82%89%E5%8F%97%E3%81%91%E5%8F%96%E3%82%8B%E3%83%88%E3%83%BC%E3%82%AF%E3%83%B3%E3%81%AE%E6%A4%9C%E8%A8%BC)
- [こちらの方がわかりやすい](https://qiita.com/sagahi/items/755782874695b8ceff20)

## そもそもJWTとは？
また、そもそもJWTとは何か？みたいなことはこの記事が理解し易い。
[Qiita 【JWT】 入門]（https://qiita.com/Naoto9282/items/8427918564400968bd2b)
これでも分かりづらいが...

**Comment by mistake-git** [comment]
https://simple-minds-think-alike.hatenablog.com/entry/rails-firebase-authentication
この記事のようにgemを使った方が簡単かも知れないが、redisが本番環境(heroku)で動くか不明。。。

**Comment by rorenge7** [comment]
アドオンで無料枠あるみたいです😄
https://elements.heroku.com/addons/heroku-redis

**Comment by mistake-git** [comment]
今回の実装でpullリクエストを実装
