### ISSUE TITLE
ディレクトリ構成の修正

### ISSUE THREAD

**Issue by rorenge7** [mistake-git/fmap-front#48]
fmap/front がリポジトリの実体となっているので、fmapの下に移動させる
例: fmap/front/src → fmap/src

参考: https://git.command-ref.com/cmd-git-mv.html

**Comment by mistake-git** [comment]
@rorenge7 
ここは少し迷っていまして、このディレクトリーにAPIも入れてしまうのがいいのか、別プロジェクトとして管理するのかどちらが良さそうでしょうか？
CI/CDの際に良さそうなのは別プロジェクトにする方法かなと思っています。

**Comment by mistake-git** [comment]
ディレクトリーを修正しました。
