### ISSUE TITLE
再利用しないコンポーネントはファイル分割しない

### ISSUE THREAD

**Issue by rorenge7** [mistake-git/fmap-front#49]
https://github.com/mistake-git/fmap/blob/04e0d0224bd73a11dba4a9d2ff6e7691e819e2ba/front/src/pages/users/PasswordEdit.tsx#L2

再利用するコンポーネントやファイルが長くなる場合にはファイル分割した方が良い。
そうでないものは分割してしまうと保守性が悪くなったり、わかりづらくなってしまうのでわざわざ分割しないべき。

PasswordEditとPasswordEditFormで合わせて100行くらいなので許容範囲かと。

**Comment by mistake-git** [comment]
ファイル分割を修正しました。
