### ISSUE TITLE
ログアウトポタンの削除

### ISSUE THREAD

**Issue by rorenge7** [mistake-git/fmap-front#51]
![image](https://user-images.githubusercontent.com/38624583/104131058-71e6be00-53b7-11eb-89b9-1ff87803d991.png)

人間は物事のはじめとおわりに注目する。
そのため目的に応じてボタン配置を工夫する必要がある。
例えば､投稿を増やしてサービス活性化を図るために投稿ボタンを端に配置するとか。

もしくは一般的なアプリと合わせてハンバーガーメニューや設定、マイページを設置。

本アプリではほとんどアカウント切り替えを行わないので不適切。
特に他のアプリと混同して誤って押下してしまうと再度ログインが必要になるのでユーザビリティがかなり損なわれる。

マイページ内にログアウトボタンを設置するとかで良さそう。

**Comment by mistake-git** [comment]
メニュー表記にしました
