### ISSUE TITLE
品詞を揃える

### ISSUE THREAD

**Issue by rorenge7** [mistake-git/fmap-front#52]
![image](https://user-images.githubusercontent.com/38624583/104131058-71e6be00-53b7-11eb-89b9-1ff87803d991.png)

動詞だったり（地図で見る、投稿する）、名詞だったり（釣果一覧、ユーザ一覧..）するので統一する。
新規投稿とか、釣果をみるとか

クリティカルな問題ではないが、サービスの質が悪く見えてしまう。

**Comment by mistake-git** [comment]
品詞の統一を行いました。
