### ISSUE TITLE
リクエストにリポジトリパターンを導入

### ISSUE THREAD

**Issue by rorenge7** [mistake-git/fmap-front#53]
リポジトリパターンというものがある。

（参考）
- https://qiita.com/mikesorae/items/ff8192fb9cf106262dbf
- https://docs.microsoft.com/ja-jp/dotnet/architecture/microservices/microservice-ddd-cqrs-patterns/infrastructure-persistence-layer-design

これは、データの受け渡しを専用のクラスに実施させることで、以下の利益を得られる。
- 別クラスの関数に切り出すことで、処理を何度も書かなくて済む
- 関数名から処理内容を理解しやすい
- リクエストの送る先を変えたときに変更箇所が少ない（例 パスを変えたいときに一箇所でOK）
- 間違ったリクエストを送りずらくなる(呼び出される側でパスを指定 & 型判定 してくれる)
- 切り出した関数だけでテストができたり、簡単にモックを入れたりと、テストしやすい

# 導入
src/repositoriesというフォルダにUsersRepostitory.tsファイルを作成して、
```UsersRepostitory.ts
import ....

export default class UsersRepository {
    public static async index(): User[] {
        // User一覧を取得する処理
        const users = await myHttpClient.get("/users");
        return users;
    }
    public static get(userId: number): User{
        // Userを取得する処理
        const users = await myHttpClient.get(`/users/${userId}`);
        
        return users;
    }
  // その他必要なら update, delete, searchなど
}
```

View側で呼び出す。
``` fuga.tsx
import UserRepository from ",/hoge/Repositories/UserRepository"

const Users = () => {
    const [users, setUsers] = useState<User[]>([])
  
    const getUsers = async(page: number) => {
        const users = await UserRepository.index();
        setUsers(users);
    }
    useEffect(() => {
        getIsers();
    },[setUsers]);

  return (
    <div>
        {users.map((user)=>(user.name))}
    </div>
  );
};
export default Users;
```

# その他
今回だとリクエストを送る先がAPI一つだけだが、グーグルアナリティクスでトラッキングしたりFluentdでロギングする場合には複数同時に送信したりする。
その場合はリポジトリパターンの恩恵を更に享受できる。

**Comment by mistake-git** [comment]
リクエストにレポジトリーパターンを導入しました
