### ISSUE TITLE
検証環境の導入

### ISSUE THREAD

**Issue by rorenge7** [mistake-git/fmap-front#54]
本番環境に直接デプロイして確認するのではなく、一度検証環境で確認してからデプロイした方が良い。
CircleCIの設定しだいでプルリクを出すと自動で検証環境にデプロイもできる。

https://github.com/FirebaseExtended/action-hosting-deploy
https://zenn.dev/yuuyamiyamae/articles/c4be0c1c700b5423ea99

API側はAWSを使用しているのでコストはかかってしまうが。

**Comment by mistake-git** [comment]
ラーニングコストがかかってしまうのでインフラはherokuに移行しました笑

**Comment by rorenge7** [comment]
了解しました笑

ci/cdは導入しない感じでしょうか？

**Comment by mistake-git** [comment]
導入したいんですがコストと相談ということで保留しております笑

**Comment by rorenge7** [comment]
circleciなら無料でできません？
それとも金銭的ではなく学習コストが問題ってことですかね？

**Comment by mistake-git** [comment]
サークルCI無料でできましたっけ？
確か前試した時無料ではなかった気がします。
AWSはNATゲートウェイが月1万ぐらいするので諦めました笑
