### ISSUE TITLE
画像投稿機能を実装したい

### ISSUE THREAD

**Issue by mistake-git** [mistake-git/fmap-front#6]
サーバーエラーが発生

**Comment by rorenge7** [comment]
https://github.com/mistake-git/fmap/blob/cff0c88b916bc74bbf2ad424470a0faa4372e0aa/front/src/components/posts/PostForm.tsx#L55
imageが文字列になってますがFileオブジェクトにすべきかと思います。
他の箇所も同様です。

その他にも問題がありそうです。
こちらのサイトを参考に修正していただけますか？
https://medium.com/@clarkjohnson_85334/uploading-photos-into-rails-6-activestorage-from-javascript-react-file-and-camera-653de99b183f

**Comment by mistake-git** [comment]
投稿機能の場合、処理が大きくなってしまうのでプロフィール画像の処理を追加しました。
URLを参考にコードを描いていたんですが、update(image: image)のとことでimageカラムがないと怒られます。attachにしてみたりしましたが、ダメみたいです。

もしも、実際に動いていないと難しそうならPCが届いてからご対応いただいても大丈夫です。
